spring:
  application:
    name: payments
  datasource:

    url: jdbc:postgresql://localhost:5432/app_db
    username: payment_user
    password: payment_pass

  flyway:
    schemas: payments
    default-schema: payments

  jpa:
    properties:
      hibernate:

        default_schema: payments

  

server:
  port: 8081